[versions]
download = "5.3.0"
kmath = "0.3.0"

[plugins]
download = { id = "de.undercouch.download", version.ref = "download" }

[libraries]
kmath-complex = { module = "space.kscience:kmath-complex", version.ref = "kmath" }
