name: Gradle build

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.1.0
          java: java11
          arch: amd64
      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          path-type: inherit
      - if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: pacman --noconfirm -S mingw-w64-x86_64-gsl
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew build --no-daemon --stacktrace
