name: Gradle build

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019, macos-12 ]
    runs-on: ${{matrix.os}}
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: liberica
      - if: matrix.os == 'windows-2019'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          path-type: inherit
      - if: matrix.os == 'windows-2019'
        shell: msys2 {0}
        run: pacman --noconfirm -S mingw-w64-x86_64-gsl
      - name: Cache konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
